### ISSUE TITLE
Shopware 5.2.8 causes error on Bootstrap.php

### ISSUE THREAD

**Issue by JulianGerhard** [shopwareLabs/SwagLightweightModule#3] opened 2016-10-10 08:53 UTC
Shopware Version 5.2.8
Clean Shop, without any other Plugins. 

Are you able to figure out, what's the problem here? We really appreciate the new Lightweight functionality - but can't use it at the moment.

Thanks in Advance!

```
Controller "ExampleModulePlainHtml" can't load failure in engine/Shopware/Components/Plugin/Bootstrap.php on line 578

Stack trace:

#0 engine/Library/Enlight/Event/Handler/Plugin.php(149): Shopware_Components_Plugin_Bootstrap->getDefaultControllerPath(Object(Enlight_Event_EventArgs))
#1 engine/Library/Enlight/Event/EventManager.php(251): Enlight_Event_Handler_Plugin->execute(Object(Enlight_Event_EventArgs))
#2 engine/Library/Enlight/Controller/Dispatcher/Default.php(368): Enlight_Event_EventManager->notifyUntil('Enlight_Control...', Array)
#3 engine/Library/Enlight/Controller/Dispatcher/Default.php(447): Enlight_Controller_Dispatcher_Default->getControllerPath(Object(Enlight_Controller_Request_RequestHttp))
#4 engine/Library/Enlight/Controller/Dispatcher/Default.php(485): Enlight_Controller_Dispatcher_Default->isDispatchable(Object(Enlight_Controller_Request_RequestHttp))
#5 engine/Library/Enlight/Controller/Front.php(223): Enlight_Controller_Dispatcher_Default->dispatch(Object(Enlight_Controller_Request_RequestHttp), Object(Enlight_Controller_Response_ResponseHttp))
#6 engine/Shopware/Kernel.php(177): Enlight_Controller_Front->dispatch()
#7 vendor/symfony/http-kernel/HttpCache/HttpCache.php(487): Shopware\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#8 engine/Shopware/Components/HttpCache/AppCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true, NULL)
#9 vendor/symfony/http-kernel/HttpCache/HttpCache.php(258): Shopware\Components\HttpCache\AppCache->forward(Object(Symfony\Component\HttpFoundation\Request), true)
#10 engine/Shopware/Components/HttpCache/AppCache.php(103): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true)
#11 shopware.php(113): Shopware\Components\HttpCache\AppCache->handle(Object(Symfony\Component\HttpFoundation\Request))
#12 {main}
```

**Comment by philippnie** [comment] 2016-10-13 19:49
I can reproduce the error, hope you can fix it soon!
Thanks in Advance

**Comment by bcremer** [comment] 2016-10-18 06:18
Thanks for reporting, this issue should be fixed with commit https://github.com/shopwareLabs/SwagLightweightModule/commit/f57bbdcc964d5c28039716f49d22e1aee868ab6c.

**Closed as completed by bcremer** 2016-10-18 06:18 UTC

**Comment by bcremer** [comment] 2016-10-18 06:20
This error was caused by commit https://github.com/shopwareLabs/SwagLightweightModule/commit/70ded8562b06c98184ce6aba8c1cfdfddbb33177.
